# NOTEBOOK SETTINGS
[notebook]
dir = "~/Documents/Notes"

# NOTE SETTINGS
[note]

# Language used when writing notes.
# This is used to generate slugs or with date formats.
language = "en"

# The default title used for new note, if no `--title` flag is provided.
default-title = "Untitled"

# Template used to generate a note's filename, without extension.
filename = "{{id}}-{{slug title}}"

# The file extension used for the notes.
extension = "md"

# Template used to generate a note's content.
# If not an absolute path, it is relative to .zk/templates/
template = "default.md"

# Configure random ID generation.

# The charset used for random IDs.
id-charset = "alphanum"

# Length of the generated IDs.
id-length = 4

# Letter case for the random IDs.
id-case = "lower"


# EXTRA VARIABLES
[extra]
author = "Tyler LaBree"

[group.personal-journal]
paths = ["personal-journal"]

[group.dune-journal]
paths = ["dune-journal"]

[group.dune-weekly]
paths = ["dune-weekly"]

[group.dune-weekly.note]
filename = "{{format-date (date 'next wednesday') '%Y_W%V'}}"
extension = "md"
template = "dune-weekly.md"

[group.dune-journal.note]
filename = "{{format-date now '%Y_%m_%d'}}"
extension = "md"
template = "dune-journal.md"

[group.personal-journal.note]
filename = "{{format-date now '%Y_%m_%d'}}"
extension = "md"
template = "personal-journal.md"

# MARKDOWN SETTINGS
[format.markdown]
# Enable support for #hashtags
hashtags = true
# Enable support for :colon:separated:tags:
colon-tags = true


# EXTERNAL TOOLS
[tool]

# Default editor used to open notes.
editor = "nvim"

# Default shell used by aliases and commands.
shell = "/bin/bash"

# Pager used to scroll through long output.
pager = "less -FIR"

# Command used to preview a note during interactive fzf mode.
fzf-preview = "bat -p --color always {-1}"

# NAMED FILTERS
[filter]
recents = "--sort created- --created-after 'last two weeks'"

# COMMAND ALIASES
[alias]
dw = "zk new --no-input $ZK_NOTEBOOK_DIR/dune-weekly"
dune = "zk new --no-input $ZK_NOTEBOOK_DIR/dune-journal"
me = "zk new --no-input $ZK_NOTEBOOK_DIR/personal-journal"
tom = "zk new --no-input --date='tomorrow' $ZK_NOTEBOOK_DIR/dune-journal"

# Edit the last modified note.
edlast = "zk edit --limit 1 --sort modified- $@"

edi = "zk edit -i"

# Edit the notes selected interactively among the notes created the last two weeks.
recent = "zk edit --sort created- --created-after 'last two weeks' --interactive"

# Show a random note.
lucky = "zk list --quiet --format full --sort random --limit 1"

# LSP (EDITOR INTEGRATION)
[lsp]

[lsp.diagnostics]
# Report titles of wiki-links as hints.
wiki-title = "hint"
# Warn for dead links between notes.
dead-link = "error"
